- hosts: all
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Iniciar el servicio de Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar archivos HTML al directorio de Apache
      copy:
        src: /index.html dest=/var/www/html/index.html
